### ISSUE TITLE
game request

### ISSUE THREAD

**Issue by torao2** [blueminder/flycast-dojo#28]
Hello, i want to request Tokyo Xtreme Racer 1 and 2 to be added

**Comment by striderdx12** [comment]
Hello, I would like to request some games to be added that I did not see available. Games include: Project Justice (Dreamcast) for Training Mode(s), Giga Wing 1 and 2 (Dreamcast), Jojo's Bizarre Adventure: Heritage For the Future (Dreamcast), Mars Matrix (Dreamcast), and Sonic Adventure 1 (Dreamcast). Thank you for your time

**Comment by Ikigaianon** [comment]
dreamcast
Bomberman Online (USA)
Worms Armageddon (USA)
Worms World Party (USA)
Street Fighter Zero 3 - Saikyo-ryu Dojo (Japan)
Sega Rally 2 (USA)
Gauntlet Legends (USA)
Virtua Cop 2 (Japan)
Pop'n Music (Japan)
Sega GT (USA]
Test Drive V-Rally (USA)
Daytona USA 2001 (Japan)
Hydro Thunder (USA)
MSR - Metropolis Street Racer (USA) (Rev A)
Test Drive Le Mans (USA)
NBA Showtime - NBA on NBC (USA)
por favor

**Comment by blueminder** [comment]
I have just added everything in this ticket with the exception of games that already exist as arcade games on the service, and Virtua Cop 2, since lightgun games still need some work for online. They should be available in the next Fightcade update.

If you wish to play any of the games for the sake of a training mode, you don't have to have a Fightcade lobby definition made for it. You can just open `flycast.exe` by itself and run the game on your own.

Closing this ticket. New game requests can go in another.
