### ISSUE TITLE
FrameAdvance, SaveState on Pause, Dump Video

### ISSUE THREAD

**Issue by BrunoRaji** [blueminder/flycast-dojo#38]
FrameAdvance/Step Frame/Single Step it's only avaiable in replay mode, it will be nice to have the feature on gameplay OffLine too

flycast-dojo don't Save/Load State on Pause, and when using Save/Load it would be great not leaving the pause state if i'm have the game paused
unlike MAME

the emulador don't have any way to Dump Video/Avi Output, when recording video directly from the Emulator, no frame is lost

Best regards,

**Comment by blueminder** [comment]
Progress on video dumping is in this ticket: https://github.com/blueminder/flycast-dojo/issues/6

**Comment by blueminder** [comment]
FrameAdvance/Step Frame/Single Step is also available in Training Mode, which is also offline.

**Comment by blueminder** [comment]
Frame advancing is in Training Mode, which is the same as Offline, but with extra features for recording and playback. You can also Save/Load from the default Menu button. This is accessible when the game is paused.

The only thing that is not already accounted for in this issue is video dumping, which is in ticket #6 . So I will close this.
