### ISSUE TITLE
Add Overlay data to .txt files

### ISSUE THREAD

**Issue by roxdox** [blueminder/flycast-dojo#41]
To keep track of what is happening on match, it would be good to export overlay data to .txt files. It helps streamers and TOs to improve what can be possible to do using Flycast

Some of them requires ROM hacks, like scores updated in real time, but some fightcade info can be exported:

"p1name"
"p1country"
"current game"

same applies for p2.

It can be updated when starting a game or spectating a match.

**Comment by blueminder** [comment]
Name and Current Game should both be doable, but Country would have to come from Fightcade somehow. At this time, Fightcade does not pass that info over.

I may ask the Fightcade devs to put it in a field, possibly. Let me know if there is other info you would like me to exfiltrate from Fightcade.

**Comment by blueminder** [comment]
The latest preview builds now have this feature included for player names and short game names. I will add country, score, and other details after the next Fightcade update, since I require the service to pass those details to the emulator.

![image](https://user-images.githubusercontent.com/504581/223269014-2cb1b437-cc99-4b3e-ac66-7ca177e90c92.png)
