### ISSUE TITLE
0.5.8 stable channel ?

### ISSUE THREAD

**Issue by 7zxkv** [blueminder/flycast-dojo#50]
Hi,

this isn't really a bug but a question.
Apparently version 0.5.8 is still considered stable in the program itself, since you can update to this older version even though you have a newer one, is this deliberate?

thanks for your work ;)

**Comment by blueminder** [comment]
It's deliberate. I have the stable channel match what's in Fightcade so that there isn't a huge mismatch against other players when people press the update button.

I'm optimistic that the included version with Fightcade will change soon, then I will keep the stable channel updated with the last compatible netplay version from there.
